#!/bin/bash

# PCI Passthrough Configuration Helper Script
# This script helps identify and configure devices for VFIO passthrough

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}PCI Passthrough Configuration Helper${NC}"
echo -e "${GREEN}========================================${NC}\n"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}This script must be run as root${NC}" 
   exit 1
fi

# Function to check IOMMU support
check_iommu() {
    echo -e "${YELLOW}Checking IOMMU support...${NC}"
    
    if dmesg | grep -qE "DMAR|AMD-Vi"; then
        echo -e "${GREEN}✓ IOMMU is enabled in kernel${NC}"
        
        # Check IOMMU groups
        if [[ -d /sys/kernel/iommu_groups/ ]] && [[ -n $(ls /sys/kernel/iommu_groups/) ]]; then
            echo -e "${GREEN}✓ IOMMU groups are present${NC}\n"
            return 0
        else
            echo -e "${RED}✗ No IOMMU groups found${NC}"
            echo "Please ensure IOMMU is enabled in BIOS/UEFI and kernel parameters"
            return 1
        fi
    else
        echo -e "${RED}✗ IOMMU is not enabled${NC}"
        echo "Add intel_iommu=on (Intel) or amd_iommu=on (AMD) to kernel parameters"
        return 1
    fi
}

# Function to list IOMMU groups
list_iommu_groups() {
    echo -e "${YELLOW}IOMMU Groups:${NC}"
    echo "----------------------------------------"
    
    for group in $(find /sys/kernel/iommu_groups/ -maxdepth 1 -type d | sort -V); do
        if [[ -n $(ls -A "$group/devices/" 2>/dev/null) ]]; then
            group_num=$(basename "$group")
            echo -e "\n${GREEN}Group $group_num:${NC}"
            for device in $group/devices/*; do
                device_id=$(basename "$device")
                device_info=$(lspci -nns "$device_id")
                echo "  $device_info"
            done
        fi
    done
    echo ""
}

# Function to identify GPUs
identify_gpus() {
    echo -e "${YELLOW}Detected GPUs:${NC}"
    echo "----------------------------------------"
    
    gpu_count=0
    declare -a gpu_ids
    declare -a gpu_descriptions
    
    while IFS= read -r line; do
        pci_id=$(echo "$line" | cut -d' ' -f1)
        vendor_device=$(echo "$line" | grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}(?=\])')
        description=$(echo "$line" | cut -d':' -f3-)
        
        gpu_ids[$gpu_count]="$vendor_device"
        gpu_descriptions[$gpu_count]="$pci_id: $description [$vendor_device]"
        
        echo "[$gpu_count] $pci_id: $description"
        echo "    Vendor:Device ID: $vendor_device"
        
        # Check if it's in use
        if [[ -e "/sys/bus/pci/devices/0000:$pci_id/driver" ]]; then
            driver=$(basename $(readlink "/sys/bus/pci/devices/0000:$pci_id/driver"))
            echo -e "    Current driver: ${YELLOW}$driver${NC}"
        fi
        
        # Find IOMMU group
        if [[ -e "/sys/bus/pci/devices/0000:$pci_id/iommu_group" ]]; then
            group=$(basename $(readlink "/sys/bus/pci/devices/0000:$pci_id/iommu_group"))
            echo "    IOMMU Group: $group"
        fi
        
        ((gpu_count++))
        echo ""
    done < <(lspci -nn | grep -E "VGA compatible controller|3D controller")
    
    # Also find associated audio devices
    echo -e "${YELLOW}Associated Audio Devices:${NC}"
    echo "----------------------------------------"
    
    while IFS= read -r line; do
        pci_id=$(echo "$line" | cut -d' ' -f1)
        vendor_device=$(echo "$line" | grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}(?=\])')
        description=$(echo "$line" | cut -d':' -f3-)
        
        echo "$pci_id: $description"
        echo "    Vendor:Device ID: $vendor_device"
        
        if [[ -e "/sys/bus/pci/devices/0000:$pci_id/iommu_group" ]]; then
            group=$(basename $(readlink "/sys/bus/pci/devices/0000:$pci_id/iommu_group"))
            echo "    IOMMU Group: $group"
        fi
        echo ""
    done < <(lspci -nn | grep -i "audio device" | grep -E "NVIDIA|AMD/ATI")
}

# Function to configure VFIO
configure_vfio() {
    echo -e "${YELLOW}Configuring VFIO...${NC}"
    
    read -p "Enter PCI IDs to pass through (comma-separated, e.g., 10de:2484,10de:228b): " pci_ids
    
    if [[ -z "$pci_ids" ]]; then
        echo -e "${RED}No PCI IDs provided${NC}"
        return 1
    fi
    
    # Create VFIO configuration
    cat > /etc/modprobe.d/vfio.conf <<EOF
# VFIO configuration for PCI passthrough
# Generated by PCI passthrough configuration script

# Devices to pass through
options vfio-pci ids=$pci_ids

# Prevent host drivers from grabbing devices
softdep nouveau pre: vfio-pci
softdep nvidia pre: vfio-pci
softdep nvidia_drm pre: vfio-pci
softdep nvidia_modeset pre: vfio-pci
softdep nvidia_uvm pre: vfio-pci
softdep amdgpu pre: vfio-pci
softdep radeon pre: vfio-pci
softdep snd_hda_intel pre: vfio-pci
EOF

    echo -e "${GREEN}✓ Created /etc/modprobe.d/vfio.conf${NC}"
    
    # Update mkinitcpio.conf
    if ! grep -q "vfio" /etc/mkinitcpio.conf; then
        echo -e "\n${YELLOW}Updating mkinitcpio.conf...${NC}"
        
        # Backup original
        cp /etc/mkinitcpio.conf /etc/mkinitcpio.conf.backup
        
        # Add VFIO modules to MODULES array
        sed -i 's/MODULES=(\(.*\))/MODULES=(\1 vfio vfio_iommu_type1 vfio_pci vfio_virqfd)/' /etc/mkinitcpio.conf
        
        # Ensure modconf hook is present
        if ! grep -q "modconf" /etc/mkinitcpio.conf; then
            sed -i 's/HOOKS=(\(.*\)block/HOOKS=(\1modconf block/' /etc/mkinitcpio.conf
        fi
        
        echo -e "${GREEN}✓ Updated /etc/mkinitcpio.conf${NC}"
    fi
    
    # Rebuild initramfs
    echo -e "\n${YELLOW}Rebuilding initramfs...${NC}"
    mkinitcpio -P
    echo -e "${GREEN}✓ Initramfs rebuilt${NC}"
    
    # Create a script to bind/unbind devices
    cat > /usr/local/bin/vfio-bind <<'EOF'
#!/bin/bash
# Helper script to bind/unbind devices to VFIO

ACTION=$1
DEVICE=$2

if [[ -z "$ACTION" ]] || [[ -z "$DEVICE" ]]; then
    echo "Usage: $0 [bind|unbind] <pci_address>"
    echo "Example: $0 bind 0000:01:00.0"
    exit 1
fi

if [[ "$ACTION" == "bind" ]]; then
    echo "$DEVICE" > /sys/bus/pci/devices/$DEVICE/driver/unbind 2>/dev/null
    echo "vfio-pci" > /sys/bus/pci/devices/$DEVICE/driver_override
    echo "$DEVICE" > /sys/bus/pci/drivers/vfio-pci/bind
    echo "Bound $DEVICE to vfio-pci"
elif [[ "$ACTION" == "unbind" ]]; then
    echo "$DEVICE" > /sys/bus/pci/drivers/vfio-pci/unbind
    echo "" > /sys/bus/pci/devices/$DEVICE/driver_override
    echo "Unbound $DEVICE from vfio-pci"
else
    echo "Invalid action. Use 'bind' or 'unbind'"
    exit 1
fi
EOF
    
    chmod +x /usr/local/bin/vfio-bind
    echo -e "${GREEN}✓ Created /usr/local/bin/vfio-bind helper script${NC}"
}

# Function to show VM XML example
show_vm_xml_example() {
    echo -e "\n${YELLOW}Example VM XML configuration for GPU passthrough:${NC}"
    echo "----------------------------------------"
    cat <<'EOF'

Add to your VM's XML configuration (virsh edit <vm-name>):

1. In the <features> section:
  <features>
    <hyperv>
      <vendor_id state='on' value='randomid'/>
    </hyperv>
    <kvm>
      <hidden state='on'/>
    </kvm>
  </features>

2. Add the PCI devices:
  <hostdev mode='subsystem' type='pci' managed='yes'>
    <source>
      <address domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </source>
    <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
  </hostdev>
  
  <hostdev mode='subsystem' type='pci' managed='yes'>
    <source>
      <address domain='0x0000' bus='0x01' slot='0x00' function='0x1'/>
    </source>
    <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
  </hostdev>

3. For better performance, add CPU pinning:
  <vcpu placement='static'>8</vcpu>
  <cputune>
    <vcpupin vcpu='0' cpuset='4'/>
    <vcpupin vcpu='1' cpuset='5'/>
    <vcpupin vcpu='2' cpuset='6'/>
    <vcpupin vcpu='3' cpuset='7'/>
    <!-- Continue for all vCPUs -->
  </cputune>

4. Enable hugepages:
  <memoryBacking>
    <hugepages/>
  </memoryBacking>

EOF
}

# Main menu
main_menu() {
    while true; do
        echo -e "\n${GREEN}PCI Passthrough Configuration Menu${NC}"
        echo "----------------------------------------"
        echo "1. Check IOMMU support"
        echo "2. List IOMMU groups"
        echo "3. Identify GPUs and audio devices"
        echo "4. Configure VFIO for passthrough"
        echo "5. Show VM XML configuration example"
        echo "6. Exit"
        echo ""
        read -p "Select an option [1-6]: " choice
        
        case $choice in
            1)
                check_iommu
                ;;
            2)
                check_iommu && list_iommu_groups
                ;;
            3)
                identify_gpus
                ;;
            4)
                configure_vfio
                echo -e "\n${YELLOW}IMPORTANT: Reboot required for changes to take effect!${NC}"
                ;;
            5)
                show_vm_xml_example
                ;;
            6)
                echo "Exiting..."
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid option${NC}"
                ;;
        esac
    done
}

# Run main menu
main_menu
